# Train 

train : True

# Model Hyperparams

seed : 42
epochs : 60
dataset : 'MaskSplitByProfileDataset' # MaskDataset, MaskSplitByProfileDataset
augmentation : 'CustomAugmentation'
cropsize : [320,256]
resize : [240,240]
batch_size : 32
model : "EfficientNet_b7" 

# Optimizer

optimizer : 'AdamW'
scheduler : 'cos'
base_lr : 0.00004
weight_decay : 1e-4
weight_decay_bias : 1e-4
bias_lr_factor : 2
warmup_epochs : 5
warmup_factor : 0.01
warmup_method : 'linear'

# Training

val_ratio : 0.2
criterion : 'cross_entropy'
lr_decay_step : 20
log_interval : 20
name : 'exp74'

# Validation

validation_interval : 1
valid_batch_size : 64

# Sampler

undersample_id : [0,3,6,9]
undersample_rate : 3
oversample_id : [13,14,16,17]
oversample_rate : 5

# Loss

sampler : 'softmax_triplet' # softmax, triplet, triplet hard
num_instance : 8
loss_type : 'triplet'
feat_norm : False
ID_loss_weight : 0.5
triplet_loss_weight : 0.5
label_smooth : False
margin : 0.3

# Test

test_data_dir : '/opt/ml/input/data/eval'
test_batch_size : 64
test_model : 'exp71'

# WANDB
 
wandb : True

# Container environment

data_dir : '/opt/ml/input/data/train/images'
model_dir : './model_output/EfficientNet_b7'
output_dir : './inference_output'

