wandb_version: 1

ID_loss_weight:
  desc: null
  value: 0.5
_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1667113740.13361
    t:
      1:
      - 1
      - 41
      - 55
      - 63
      2:
      - 1
      - 41
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.8.13
      5: 0.13.4
      8:
      - 5
augmentation:
  desc: null
  value: CustomAugmentation
base_lr:
  desc: null
  value: 0.0004
batch_size:
  desc: null
  value: 32
bias_lr_factor:
  desc: null
  value: 2
cosine_margin:
  desc: null
  value: 0.5
cosine_scale:
  desc: null
  value: 30
criterion:
  desc: null
  value: cross_entropy
cropsize:
  desc: null
  value:
  - 320
  - 256
data_dir:
  desc: null
  value: /opt/ml/input/data/train/images
dataset:
  desc: null
  value: MaskSplitByProfileDataset
epochs:
  desc: null
  value: 100
feat_norm:
  desc: null
  value: false
gamma:
  desc: null
  value: 0.1
label_smooth:
  desc: null
  value: false
log_interval:
  desc: null
  value: 20
loss_type:
  desc: null
  value: triplet
lr_decay_step:
  desc: null
  value: 20
margin:
  desc: null
  value: 0.3
model:
  desc: null
  value: EfficientNet_b0
model_dir:
  desc: null
  value: ./model_output/EfficientNet_b0
momentum:
  desc: null
  value: 0.9
name:
  desc: null
  value: exp
num_instance:
  desc: null
  value: 8
optimizer:
  desc: null
  value: SGD
output_dir:
  desc: null
  value: ./inference_output
resize:
  desc: null
  value:
  - 240
  - 240
sampler:
  desc: null
  value: softmax_triplet
scheduler:
  desc: null
  value: cos
seed:
  desc: null
  value: 42
solver_seed:
  desc: null
  value: 1234
steps:
  desc: null
  value:
  - 40
  - 70
test_batch_size:
  desc: null
  value: 64
test_data_dir:
  desc: null
  value: /opt/ml/input/data/eval
test_model:
  desc: null
  value: exp59
train:
  desc: null
  value: true
triplet_loss_weight:
  desc: null
  value: 0.5
val_ratio:
  desc: null
  value: 0.2
valid_batch_size:
  desc: null
  value: 64
validation_interval:
  desc: null
  value: 1
wandb:
  desc: null
  value: true
warmup_epochs:
  desc: null
  value: 5
warmup_factor:
  desc: null
  value: 0.01
warmup_method:
  desc: null
  value: linear
weight_decay:
  desc: null
  value: 0.0001
weight_decay_bias:
  desc: null
  value: 0.0001
