wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1667285962.508462
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.8.5
      5: 0.13.4
      8:
      - 5
augmentation:
  desc: null
  value: CustomAugmentation
batch_size:
  desc: null
  value: 16
criterion:
  desc: null
  value: f1
data_dir:
  desc: null
  value: /opt/ml/input/data/train/images
dataset:
  desc: null
  value: MaskSplitByProfileDataset
epochs:
  desc: null
  value: 10
log_interval:
  desc: null
  value: 20
lr:
  desc: null
  value: 2.0e-05
lr_decay_step:
  desc: null
  value: 20
model:
  desc: null
  value: EfficientNet_b0
model_dir:
  desc: null
  value: ./model/EfficientNet_b0
name:
  desc: null
  value: exp6
optimizer:
  desc: null
  value: Adam
output_dir:
  desc: null
  value: ./inferenceoutput
resize:
  desc: null
  value:
  - 256
  - 192
seed:
  desc: null
  value: 42
test_batch_size:
  desc: null
  value: 64
test_data_dir:
  desc: null
  value: /opt/ml/input/data/eval
test_model:
  desc: null
  value: exp6
val_ratio:
  desc: null
  value: 0.2
valid_batch_size:
  desc: null
  value: 64
validation_interval:
  desc: null
  value: 1
wandb:
  desc: null
  value: true
