# Model Hyperparams

seed : 42
epochs : 1
dataset : 'MaskSplitByProfileDataset' # MaskDataset, MaskSplitByProfileDataset
augmentation : 'BaseAugmentation'
batch_size : 64
model : "BaseModel" 

# Training

optimizer : 'SGD'
lr : 0.001
val_ratio : 0.2
criterion : 'cross_entropy'
lr_decay_step : 20
log_interval : 20
name : 'exp'

# Validation

validation_interval : 10
valid_batch_size : 1000

# Container environment

data_dir : '/opt/ml/input/data/train/images'
model_dir : './model'

