wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1667303930.745928
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 23
      4: 3.8.5
      5: 0.13.4
      8:
      - 5
